Improve subcommander
Subcommander is improving to the point where it is useful; cleaning up
for pushing to Github.

diff --git a/bin/subcommander b/bin/subcommander
--- a/bin/subcommander
+++ b/bin/subcommander
@@ -2,15 +2,13 @@
 
 # subcommander
 #
-# Several advanced tools (like git, subversion, cvs, zip, etc.
-# follow a pattern where the main tool is called followed by a
-# subcommand specific to that system. This acts as a somewhat
-# informal namespace for executables.
+# Several advanced tools (like git, subversion, cvs, zip, etc.  follow a
+# pattern where the main tool is called followed by a subcommand specific to
+# that system. This acts as a somewhat informal namespace for executables.
 #
-# This script attempts to encapsulate this pattern. It first walks
-# up the directory tree looking for a .$0.context file to source.
-# Then it looks for an executable named $0.d/$1 or $0.d/$1.* to
-# execute.
+# This script attempts to encapsulate this pattern. It first walks up the
+# directory tree looking for a .$0.context file to source. Then it looks for an
+# executable named $0.d/$1 or $0.d/$1.* to execute.
 #
 # Setup:
 #
@@ -30,14 +28,135 @@
 # 
 # From anywhere within foo/bar:
 # 	'mytool status'
-# will source foo/bar/.mytool.context, and then execute bin/mytool.d/status with the following variables set:
+# will source foo/bar/.mytool.context, and then execute bin/mytool.d/status
+# with the following variables set:
 # 
 # TODO: finish this
 #
-# The following subcommands are always available, though they may be overridden if defined in a subtool:
-#
-#	exec 	execute a shell or any other executable, and store the context in the environment. (disables context file searching)
-#
-#	help COMMAND	gives more information about a particular subcommand.
-# 	
-# TODO: how to integrate with prompt and/or window title?
+# TODO: Integrate with prompt and/or window title?
+
+verbose=
+basename="`basename $0`"
+
+subcommandsdir="$0.d"
+
+# Find the nearest context file in the directory hierarchy.
+[ "$skip_context_discovery" ] || {
+	discovered_contextfile=`acquire ".$basename.context"`
+	discovered_context=`dirname "$discovered_contextfile"`
+}
+
+# This names the environment variable in which to save contexts.
+[ "$context_envname" ] || \
+	context_envname="`echo $basename|tr 'a-z ' 'A-Z_'`_CONTEXT"
+
+eval "environment_context=\$$context_envname"
+
+# Choose "warn", "ignore", or "abort"
+[ "$context_mismatch_action" ] || \
+	context_mismatch_action="warn"
+
+list_subcommands () {
+	local seen
+	if [ -d "$subcommandsdir" ]; then
+		for f in "$0.d"/*; do
+			[ -x "$f" ] || continue
+			[ $seen ] || {
+				echo "Available $basename commands are:"
+				seen=1
+			}
+			printf \
+				"   %-10s %s\n" \
+				"`basename \"$f\"`" \
+				"`sed -n '1,10s/^.\{0,4\}desc\(ription\)\?\s*[:=]\s*//Ip' \"$f\"`"
+		done
+		[ $seen ] || fmt <<-EOF
+		Subcommands directory $subcommandsdir contains no executables. Place
+		executable files here to enable them as sub-commands of '$basename'.
+		EOF
+	else
+		fmt <<-EOF
+		Subcommands directory $subcommandsdir does not exist. Place executable
+		files there to enable them as sub-commands of '$basename'.
+		EOF
+	fi
+}
+
+usage () {
+	echo "usage: $basename COMMAND [ARGS]"
+	echo
+	list_subcommands
+}
+
+# Functions which take messages as standard input
+warn () {
+	fmt >&2
+}
+ignore () {
+	cat > /dev/null
+}
+abort () {
+	warn; exit $1
+}
+usage_abort () {
+	usage
+	echo
+	abort $1
+}
+
+# Were we called with any arguments at all?
+[ $# -gt 0 ] || usage_abort 2 <<-EOF
+	No COMMAND specified.
+	EOF
+
+subcommandbase="$1"
+subcommand="$subcommandsdir/$1"
+shift; subcommandargs="$@"
+
+# If context is manually set, ensure it exists.
+if [ "$environment_context" ]; then
+	environment_contextfile="$environment_context/.$basename.context"
+
+	[ -f "$environment_contextfile" ] || abort 3 <<-EOF
+	The context specified by $context_envname does not exist:
+	$environment_contextfile not found.
+	EOF
+fi
+
+# If both are set, see if one differs from the other. (Possibly confused user.)
+if [ "$environment_contextfile" -a "$discovered_contextfile" ]; then
+	if [ ! "$environment_contextfile" -ef "$discovered_contextfile" ]; then
+		$context_mismatch_action <<-EOF
+		Warning: Context specified by $context_envname=$environment_context
+		differs from and overrides context discovered at $discovered_context.
+		Be sure that this is what you intend.
+		EOF
+	fi
+fi
+
+# Prefer environment-specified context over discovered context.
+# TODO: prefer argument-specified context over both.
+if [ "$environment_contextfile" ]; then
+	contextfile="$environment_contextfile"
+elif [ "$discovered_contextfile" ]; then
+	contextfile="$discovered_contextfile"
+fi
+
+# Source context or mention that it is non-existent.
+if [ "$contextfile" ]; then
+	[ "$verbose" ] && warn "Sourcing context $contextfile..."
+	set -a
+	. "$contextfile"
+	set +a
+else
+	[ $verbose ] && warn "Note: no context was found."
+fi
+
+# Check to ensure subcommand is an executable
+[ -x "$subcommand" ] || abort <<-EOF
+	error: unknown $basename command: $subcommandbase.
+	EOF
+
+# Launch subcommand.
+export SUBCOMMANDER="$0"
+exec "$subcommand" "$subcommandargs"
